### ISSUE TITLE
Anti xD-Spam System 

### ISSUE THREAD

**Issue by Naaaaaam** [PolylymerDE/NoRiskClientBotRemastered#11]
xD ist schon insane schlimm. Aber die die mit xDDDDDDDDDDDDD kommen sind Monster, daher sollte ein Auto Kick passieren ab einem xDDD ab dem 3 d weil da das alter unter 0 fällt und somit das Leben auf dem Discord nicht mehr notwendig ist.

**Comment by mooziii** [comment]
xDDDDDDDDDDDDD
