### ISSUE TITLE
Idee: Neue Commands!

### ISSUE THREAD

**Issue by NooMacroo** [PolylymerDE/NoRiskClientBotRemastered#12]
Für die blacklist:
@NoRiskClientBot = Text wo er alle seine commands listet.
Zweiter Text für "offline" "error" "download" damit nicht immer das gleiche kommt
Moin EnderDragonWings = jung2abusieue

Für die stats:
Bans und unbans
Kicks
Reports
Benutzte commands
Seit wann man discord user ist
Meist benutztes Wort
Meist gepingte Person
Von wem man am meisten gepingt wurde

Allgemeine Commands
/12 = Bild von wo es kommt
/survival = random survival Zitate
/Helper = Erklärung der Rolle
/Supporter = Erklärung der Rolle
/Admin = Erklärung der Rolle + nicht pingen sollen erwähnen
/Contributor = Erklärung mit github link
/Code = So etwas wie "Der Client ist nicht OpenSource aber der installer" und dann der jeweilige Link

**Comment by Wurliiii** [comment]
Niemand hat nach gefragt!

**Comment by NooMacroo** [comment]
> Niemand hat nach gefragt!

Ich mafh dich kaputt

**Comment by Wurliiii** [comment]
Who asked?
