### ISSUE TITLE
Auto Antwort bei ! Commands 

### ISSUE THREAD

**Issue by 0hAlex** [PolylymerDE/NoRiskClientBotRemastered#20]
Sollte nochmal jemand einen command mit ! Anstatt / benutzen (da gibt es noch so einige) könnte eine Auto Antwort sagen dass man die commands mit / bilden muss

**Comment by mooziii** [comment]
wenn ich das mache kann ich direkt wieder ! commands adden
außerdem ist der dc tot? xd

**Comment by 0hAlex** [comment]
> wenn ich das mache kann ich direkt wieder ! commands adden
> außerdem ist der dc tot? xd

Der ist nicht wirklich tot und dass Leute ! Commands benutzen wollen passiert gar nicht so selten

**Comment by Wurliiii** [comment]
Der bot soll aber nicht helprr ersetzen :/
