### ISSUE TITLE
Add "obsi" reaction

### ISSUE THREAD

**Issue by Naaaaaam** [PolylymerDE/NoRiskClientBotRemastered#6]
Wenn jemand obsi schreibt antwortet der bot sofort mit dem obsi emote damit keiner ohne obsi bleibt!

**Comment by Naaaaaam** [comment]
Und nicht als Reaktionen sondern wr schickt es wirklich, oder als Reaktion ist eig egal

**Comment by mooziii** [comment]
> 
> 
> Wenn jemand obsi schreibt antwortet der bot sofort mit dem obsi emote damit keiner ohne obsi bleibt!

sowas gibt es tatsächlich schon

**Comment by Naaaaaam** [comment]
:/

**Comment by Naaaaaam** [comment]
Einfach gescamt
