### ISSUE TITLE
xD = 12 3DIGITS OLD SUP BOT MEME KAPUTT

### ISSUE THREAD

**Issue by NooMacroo** [PolylymerDE/NoRiskClientBotRemastered#8]
HALLO 12 IST KAPUTT BIZTE BITTE VGIBT CONTIRBUTORE
![Screenshot_20210531-211431_Discord-Beta](https://user-images.githubusercontent.com/81960499/120234098-8b4db100-c257-11eb-8599-0ca811969ff7.jpg)

**Comment by Naaaaaam** [comment]
Tf so geht Github nicht

**Comment by Naaaaaam** [comment]
Und das ist kein Bug sondern nur ein Problem der Verzögerung, wenn der bot reagiert

**Comment by Wurliiii** [comment]
> HALLO 12 IST KAPUTT BIZTE BITTE VGIBT CONTIRBUTORE
> ![Screenshot_20210531-211431_Discord-Beta](https://user-images.githubusercontent.com/81960499/120234098-8b4db100-c257-11eb-8599-0ca811969ff7.jpg)

meme

**Comment by Wurliiii** [comment]
meme

**Comment by mooziii** [comment]
das was nam sagt

**Comment by NooMacroo** [comment]
Nam halts maul

**Comment by NooMacroo** [comment]
> meme

Sorry

**Comment by Naaaaaam** [comment]
@mooziii kann man leute von nen github projekt bannen?

**Comment by mooziii** [comment]
ne
