### ISSUE TITLE
IDEE DAMIT DER BOT NICHT MEHR KERNBEHINDERT WIRKT

### ISSUE THREAD

**Issue by NooMacroo** [PolylymerDE/NoRiskClientBotRemastered#9]
Idee: Der Bot soll nicht so eingeschränkt sein und verschiedene Texte sagen können auf bestimmte fragen. Würde auch paar Texte selbst verfassen @Indikativ HI

**Comment by mooziii** [comment]
wie jeds

**Comment by Naaaaaam** [comment]
Glaube er will dass der bot antworten kann

**Comment by Naaaaaam** [comment]
Also du sagst. Hey Bot wie gehts? Und er: Besser wenn ich Obsi hätte

**Comment by NooMacroo** [comment]
> wie jeds

ER SOLL VERSCHIEDENE ANTWORTEN HABEN ODER AUCH SICH MIT USERN EIN WENIG UNTERHALTEN KÜNNENNNE

**Comment by Wurliiii** [comment]
@NooMacroo weirdchamp

**Comment by Wurliiii** [comment]
**hsmfudliad ih bin geil**

**Comment by mooziii** [comment]
bitte keine random kommentare

**Comment by NooMacroo** [comment]
> @NooMacroo weirdchamp

Warum? SORRY😭

**Comment by Wurliiii** [comment]
wurm nwichz

**Comment by Wurliiii** [comment]
oh moziii tut mir leid

**Comment by mooziii** [comment]
:crown:

**Comment by Wurliiii** [comment]
aber butte pack z cokm über con matrix und ich rkeigen sonsg  anfall

**Comment by MatrixCodeDE** [comment]
xD
